fix: made update to faq page
workshopapps/loveletterwriter.web pull request #250
Opened 2022-12-01 20:27 UTC by yvehogan

2022-12-01 23:45 UTC, Idimmusix requested changes
Kindly pull and merge conflicts, then pussh again.

2022-12-02 02:14 UTC, yvehogan commented
no conflict to merge, it says working tree is clean on my end, when i git pull origin dev

2022-12-02 06:22 UTC, juicio8 submitted a review, later dismissed

2022-12-02 06:24 UTC, juicio8 approved these changes

2022-12-02 06:25 UTC, merged